
## NumPy

Python's fundamental library for fast and efficient scientific computing and data analysis. 

Key features include:
* The multidimensional array (also known as ndarray, NumPy array)
* Fast and efficient functions to interact with ndarrays
* Standard mathematical functions for working with ndarrays
* Tools for integrating code written in C, C++, and Fortran

From the docs (https://numpy.org/doc/stable/user/quickstart.html): 
> "NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called axes."

This notebook covers the following concepts:

1. Creating ndarrays
2. Ndarray attributes
3. Arithmetic operators
4. Slicing and indexing
5. Universal functions and vectorization

### Sources
1. W. McKinney, “NumPy Basics: Arrays and Vectorized Computation,” in _Python for Data Analysis_, Sebastopol, CA: O'Reilly Media, Inc, USA, 2013, pp. 79–110. 
2. J. VanderPlas, "Introduction to NumPy," in _Python Data Science Handbook_, O'Reilly Media, Inc. November 2016. [Online]. Available: https://jakevdp.github.io/PythonDataScienceHandbook/.
3. “NumPy Reference,” _NumPy Reference - NumPy v1.19 Manual_, 29-Jun-2020. [Online]. Available: https://numpy.org/doc/stable/reference/. 
---

In [1]:
# Import the NumPy library
import numpy as np

# Import the random.default_rng subpackage
from numpy.random import default_rng

In [2]:
# Access the numpy version
print(np.__version__)

1.19.2


### Creating a new NumPy array

* `array()` //- fundamental constructor; requires list or tuple of values as input
* `arange(start, stop, step)` //- create a linear sequence
* `zeros()` //- creates an array that is filled with 0s
* `ones()` //- creates an array filled with ones
* `empty()` //- creates a new array with values not explicitly set

Use the `array()` constructor, which takes a list or tuple of values.

In [3]:
# print(np.array([2,3,4])) # Input could be tuple instead of list
print(np.array([2,3,4], dtype=float)) # Can also provide the data type as input (optional)

[2. 3. 4.]


Add a dimension by adding brackets where appropriate.

In [4]:
print(np.array([[2,3], [4,5], [6,7], [7,8]]))

[[2 3]
 [4 5]
 [6 7]
 [7 8]]


NumPy promotes elements so the entire array is of one type.

In [5]:
# Create a NumPy array from a Python list
myList = [1, 97, 32, 4.0, -16, 0]
myArray = np.array(myList)
print(myArray) # notice that integers have been "promoted" to floating point numbers

[  1.  97.  32.   4. -16.   0.]


Use `arange()`, which is similar to the built-in `range()` function.

In [6]:
# Use .arange() to create a new array 
print(np.arange(start=10, stop=20, step=2))

[10 12 14 16 18]


In [7]:
# Create a two-dimensional array with arange() and shape()
mat = np.arange(0,75,5) # Creates a vector with 15 elements
mat.shape = (3,5) # Reshapes the vector into a two-dimentional array (3 rows * 5 cols)
print(mat)

[[ 0  5 10 15 20]
 [25 30 35 40 45]
 [50 55 60 65 70]]


### NumPy Array Attributes
#### Diminsions, shape, size, and data type

In [8]:
mat

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70]])

In [9]:
# View the number of dimensions of the ndarray
mat.ndim

2

In [10]:
# View the shape of the ndarray
mat.shape

(3, 5)

In [11]:
# View the number of attributes in the ndarray
mat.size

15

In [12]:
mat.dtype # Get the data type of the elements in the array

dtype('int64')

### Accessing elements: indexing and slicing
#### Indexing

In [13]:
# We created myArray earlier...
print(myArray)

[  1.  97.  32.   4. -16.   0.]


Access a single element with square brackets.

In [14]:
print(myArray[1])

97.0


In [15]:
# We created the 2D array mat earlier...
print(mat)

[[ 0  5 10 15 20]
 [25 30 35 40 45]
 [50 55 60 65 70]]


Indexing a two-dimensional arrray with a single index returns the entire row at that index.

In [16]:
print(mat[1])

[25 30 35 40 45]


To access a single element, pass the row and column indices separated by a comma.

In [17]:
# Access elements with comma-separated indices
print(mat[1,2])

35


<img src='../../forDataAnalysis/Images/indexing.png' style='width: 400px;' align='left'/>

Modify (set) elements with the same syntax.

In [18]:
mat[2,-1] = -1
print(mat)

[[ 0  5 10 15 20]
 [25 30 35 40 45]
 [50 55 60 65 -1]]


#### Slicing: accessing subarrays
NumPy slicing syntax follows that of the Python list: `x[start:stop:step]`, with default values `start = 0`, `stop = `*`size of dimension`*, `step = 1`.

Slice with a 1-dimensional array.

In [19]:
# Slice one-dimensional arrays with [:] syntax
print(myArray)

[  1.  97.  32.   4. -16.   0.]


In [20]:
print(myArray[1:4])

[97. 32.  4.]


Slice with a 2-dimensional array by using comma-separated indices (again). 

In [21]:
mat

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, -1]])

In [22]:
# Return the first column
print(mat[:,0])

[ 0 25 50]


In [23]:
print(mat[0,:]) # return the first row with all columns

[ 0  5 10 15 20]


In [24]:
# Return the first and second rows and all columns
print(mat[0:2,:])

[[ 0  5 10 15 20]
 [25 30 35 40 45]]


In [25]:
print(mat[0:2,0:3]) # return elements that are in rows 1-2 AND in columns 1-3

[[ 0  5 10]
 [25 30 35]]


### Vectorization and universal functions (ufuncs)

NumPy allows users to execute batch operations without writing for loops. This is usually called _vectorization_, and is one of the key elements in NumPy's speed and efficiency. The NumPy docs give the following definition of vectorization:

> Optimizing a looping block by specialized code. In a traditional sense, vectorization performs the same operation on multiple elements with fixed strides between them via specialized hardware. Compilers know how to take advantage of well-constructed loops to implement such optimizations. NumPy uses vectorization to mean any optimization via specialized code performing the same operations on multiple elements, typically achieving speedups by avoiding some of the overhead in looking up and converting the elements.

Vectorized operations are usually implemented through `universal functions` or `ufuncs`, functions that operate on ndarrays in an element-by-element fashion. Per the NumPy docs, a `ufunc` is

> ... a “vectorized” wrapper for a function that takes a fixed number of specific inputs and produces a fixed number of specific outputs.

Some examples include `sqrt()` and `exp()`, which are _unary_ ufuncs; arithmetic operations, like `+`, `-`, `*`; comparison operators, like `<`, `>=`, `!=`; and many others.

To show the difference in efficiency, let's compare a simple operation exectuted with a loop against the same operation executed with a using NumPy's vectorized capability. 

The following example is derived from the example in: _J. VanderPlas, Python Data Science Handbook. O'Reilly Media, Inc. November 2016. Available: https://jakevdp.github.io/PythonDataScienceHandbook/._

In [26]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

In [27]:
rng = default_rng(12345) # Constuctor for random number generator
values = rng.integers(1, 10, size=5)
compute_reciprocals(values)

array([0.14285714, 0.33333333, 0.125     , 0.33333333, 0.5       ])

In [28]:
big_array = rng.integers(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

1.68 s ± 69.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Completing this opertion with a loop takes a significant amount of time. Enter _vectorized_ operations. 

The snippet below creates the same output as the loop above using vectorized operations. 

In [29]:
%timeit (1.0 / big_array)

1.41 ms ± 274 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Always consider whether a loop in Python can be replaced by a vectorized operation.

### Array operations


In [30]:
a = np.array([10,20,30,40,50])
b = np.arange(2,7)

In [31]:
a

array([10, 20, 30, 40, 50])

In [32]:
b

array([2, 3, 4, 5, 6])

For operations where the length of the two arrays is equal, operations occur on an element-by-element basis.

In [33]:
a-b
# a*b
# a%b

array([ 8, 17, 26, 35, 44])

When one of the values in the expression is a scalar, the scalar is used as an operand against all values in the array. 

In [34]:
a + 7
# b * 3

array([17, 27, 37, 47, 57])

#### Select ufuncs

**Absolute value** works like Python's built-in function using `np.abs()`.

In [35]:
-a

array([-10, -20, -30, -40, -50])

In [36]:
np.abs(-a)

array([10, 20, 30, 40, 50])

#### Exponents

In [37]:
x = np.array([1, 2, 4, 10])
print(x)

[ 1  2  4 10]


In [38]:
# e^x
print(np.exp(x))

[2.71828183e+00 7.38905610e+00 5.45981500e+01 2.20264658e+04]


In [39]:
# 2^x
print(np.power(2, x))

[   2    4   16 1024]


In [40]:
print(np.power(3, x))

[    3     9    81 59049]


#### Logarithms

In [41]:
print(np.log(x))

[0.         0.69314718 1.38629436 2.30258509]


In [42]:
print(np.log2(x))

[0.         1.         2.         3.32192809]


In [43]:
print(np.log10(x))

[0.         0.30103    0.60205999 1.        ]


Many other ufuncs are available in NumPy, including trigonomic functions, conversions, rounding, and more. Refer to the documentation for more information.

### Selecting elements conditionally

In [44]:
print(myArray)

[  1.  97.  32.   4. -16.   0.]


An expression using conditional logic creates a boolean array, where the True/False values at each index of the resulting array correspond to the outcome of the test against that element in the original ndarray.

In [45]:
myArray > 4

array([False,  True,  True, False, False, False])

The Boolean array can be used to select items that correspond to `True` values of the expression.

In [46]:
myArray[myArray>4]

array([97., 32.])

This selection returns a **view** on the original array, not a copy.

In [47]:
newArray = myArray.copy()
newArray[newArray>4] = -111
print(newArray)

[   1. -111. -111.    4.  -16.    0.]


#### Another example

In [48]:
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [49]:
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [50]:
print(a[b])

[ 5  6  7  8  9 10 11]


**Select elements with multiple criteria**

In [51]:
print(myArray[(myArray > 4) & (myArray < 96)])

[32.]


In [52]:
print(myArray[((myArray < 4) | (myArray > 96))])

[  1.  97. -16.   0.]


### Aggregation

NumPy has fast built-in aggregation functions for working on arrays.

In [53]:
a = np.arange(2, 10, dtype='float32')
print(a)

[2. 3. 4. 5. 6. 7. 8. 9.]


Summation

In [54]:
print(np.sum(a))

44.0


Minimum and Maximum

In [55]:
print(np.max(a))
# print(np.min(a))

9.0


#### Compute aggregates along a specified axis

In [56]:
M = rng.integers(10,size=(3, 4))
print(M)

[[1 7 4 2]
 [4 0 5 4]
 [3 1 6 8]]


In [57]:
M.sum()

45

Aggregate by column with `axis = 0`.

In [58]:
M.sum(axis=0)

array([ 8,  8, 15, 14])

Aggregate by rows with `axis = 1`.

In [59]:
M.sum(axis=1)

array([14, 13, 18])

See the NumPy documentation for a list of aggregate functions: https://numpy.org/doc/stable/reference/arrays.ndarray.html#array-ndarray-methods.

### American National Election Survey 1996
This section uses a built-in dataset found in the statsmodels package: American National Election Survey 1996
https://www.statsmodels.org/devel/datasets/generated/anes96.html. To access the dataset, first install statsmodels (if not already installed: `pip install statsmodels`. Next, `import statsmodels.api as sm`. You can view a description of the data with `print(sm.datasets.anes96.NOTE)`. Load the dataset with `data = sm.datasets.anes96.load_pandas()`, and access the dataframe with `data.data`. View a small portion of the data with the `head()` method. Use the `values` attribute to get the array of values.


In [60]:
import statsmodels.api as sm
print(sm.datasets.anes96.NOTE)

::

    Number of observations - 944
    Number of variables - 10

    Variables name definitions::

            popul - Census place population in 1000s
            TVnews - Number of times per week that respondent watches TV news.
            PID - Party identification of respondent.
                0 - Strong Democrat
                1 - Weak Democrat
                2 - Independent-Democrat
                3 - Independent-Indpendent
                4 - Independent-Republican
                5 - Weak Republican
                6 - Strong Republican
            age : Age of respondent.
            educ - Education level of respondent
                1 - 1-8 grades
                2 - Some high school
                3 - High school graduate
                4 - Some college
                5 - College degree
                6 - Master's degree
                7 - PhD
            income - Income of household
                1  - None or less than $2,999
                2  - $3,000-$4,9

In [61]:
data = sm.datasets.anes96.load_pandas()
anes = data.data
anes.head()

popul  TVnews  selfLR  ClinLR  DoleLR  PID   age  educ  income  vote  \
0    0.0     7.0     7.0     1.0     6.0  6.0  36.0   3.0     1.0   1.0   
1  190.0     1.0     3.0     3.0     5.0  1.0  20.0   4.0     1.0   0.0   
2   31.0     7.0     2.0     2.0     6.0  1.0  24.0   6.0     1.0   0.0   
3   83.0     4.0     3.0     4.0     5.0  1.0  28.0   6.0     1.0   0.0   
4  640.0     7.0     5.0     6.0     4.0  0.0  68.0   6.0     1.0   0.0   

   logpopul  
0 -2.302585  
1  5.247550  
2  3.437208  
3  4.420045  
4  6.461624

In [62]:
anes_vals = anes.values

In [63]:
# View the (a) number of dimensions, (b) size, and (c) shape of the array.
anes_vals.ndim

2

In [64]:
anes_vals.size

10384

In [65]:
anes_vals.shape

(944, 11)

View the first 10 elements in the first column.

In [66]:
anes_vals[:10,0]

array([   0.,  190.,   31.,   83.,  640.,  110.,  100.,   31.,  180.,
       2800.])

How many respondants answered 0 to the question corresponding to PID (column 6)?

In [67]:
np.sum(anes_vals[:,5]==0.0)

200

What is the maximum value in the age column?

In [68]:
np.max(anes_vals[:,6])

91.0

How many respondants report a household income between \\$20,000 and \\$90,000?

In [69]:
np.sum((anes_vals[:,8]>=13) & (anes_vals[:,8]<23))

620

Standardized variables are obtained by subtracting the mean of the variable and by dividing by the standard deviation of that same variable. Standardize the age column.

In [70]:
ageMean = np.mean(anes_vals[:,6])
ageStd = np.std(anes_vals[:,6])
anes_vals[:,6] = (anes_vals[:,6] - ageMean) / ageStd
print(anes_vals[:,6])

[-6.72788062e-01 -1.64754019e+00 -1.40385216e+00 -1.16016412e+00
  1.27671619e+00 -1.58661818e+00  1.82501426e+00 -1.58661818e+00
 -9.77398101e-01 -4.90022039e-01 -1.28200814e+00 -9.77398101e-01
 -1.52569617e+00 -3.07256016e-01  1.64224823e+00  9.11184139e-01
  6.67496108e-01 -1.40385216e+00  2.41042054e-01 -6.72788062e-01
  2.49515634e+00 -1.64754019e+00 -1.22108613e+00 -1.85412000e-01
 -1.24489993e-01 -1.58661818e+00 -4.29100031e-01 -4.29100031e-01
  5.82760307e-02 -7.94632078e-01 -1.28200814e+00  7.89340124e-01
 -9.16476094e-01 -9.77398101e-01 -8.55554086e-01  6.06574101e-01
  2.25146831e+00  1.70317024e+00 -1.70846219e+00 -2.64597703e-03
  2.41042054e-01 -4.29100031e-01 -1.52569617e+00 -7.33710070e-01
 -2.46334008e-01  1.76409225e+00 -1.24489993e-01  2.49515634e+00
 -6.35679848e-02 -1.52569617e+00  1.27671619e+00 -5.50944047e-01
  1.33763819e+00  1.21579418e+00  2.49515634e+00  1.27671619e+00
  1.76409225e+00  1.52040422e+00 -6.11866055e-01  1.33763819e+00
 -8.55554086e-01 -7.94632

***


# pandas
> pandas is a python package providing fast, flexible, and expressive data structures designed to make working with “relational” or “labeled” data both easy and intuitive. It aims to be the fundamental high-level building block for doing practical, real world data analysis in Python.



#### Features include:

* Explore, clean, and process tabular data
* Two primary data structures: the Series (1-dimensional) and the DataFrame (2-dimensional). 
* Read/write support for many different formats (CSV, XLS, HTML, JSON, SQL, and others)
* Provides methods for plotting through Matplotlib wrapper
* Great documentation, including guides for those familiar with R, Stata, SAS, and SQL: https://pandas.pydata.org/docs/.

#### Objectives
* Creating objects
* Viewing objects
* Selection
* Operations
* Grouping 
* Categoricals
* Reshaping data
* Plotting

In [71]:
# import numpy as np
import pandas as pd # Importing pandas as "pd" is the convention

## Data Structures: Series and DataFrame

### Series

> A pandas Series is a one-dimensional array with axis labels.

The Series constructor is `pd.Series(data, index)`, where index is optional. The data parameter can take arguments of many different forms:
* Scalar value
* Python List, Dict, Set
* NumPy Array

#### Create a Series by passing a scalar


In [72]:
pd.Series(1, index=['a','b','c','d'])

a    1
b    1
c    1
d    1
dtype: int64

#### Create a Series by passing a Python list

In [73]:
pd.Series([4,3,-5,8])

0    4
1    3
2   -5
3    8
dtype: int64

Indices are integers by default, but can be set explicitly. Additionally, they can consist of values of any desired data type. This is the primary difference between a 1-dimensional NumPy array and the pandas Series.

In [74]:
# We can also explicitly create a named index
s = pd.Series([4,3,-5,8], index=['a','b','c','d'])
s

a    4
b    3
c   -5
d    8
dtype: int64

The `values` attribute contains a NumPy array. The `index` attribute contains the Series index.

In [75]:
s.values

array([ 4,  3, -5,  8])

In [76]:
s.index

Index(['a', 'b', 'c', 'd'], dtype='object')

#### Create a Series with a Python dictionary

In [77]:
shapes = {'circle': 0,
          'triangle': 3,
          'square': 4,
          'pentagon': 5,
          'hexagon': 6,
          'heptagon':7,
          'octagon':8}

The **dict** keys become the Series **indices**. 

In [78]:
shapesSeries = pd.Series(shapes)
shapesSeries

circle      0
triangle    3
square      4
pentagon    5
hexagon     6
heptagon    7
octagon     8
dtype: int64

### DataFrame

The **DataFrame** object is a tabular data structure containing an ordered collection of columns.
* Spreadsheet-like
* Each column can contain different data types (numeric, string, boolean, etc.)
* Has both a row and column index
* Can be thought of as a dict of Series

#### Create a DataFrame by passing a NumPy array

In [79]:
dates = pd.date_range('20200101', periods=6) # to be used as the index

In [80]:
dates

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06'],
              dtype='datetime64[ns]', freq='D')

In [81]:
# Create a DataFrame object with a NumPy array of size 6x4 with 
# samples from the standard normal distribution
# rng = np.random.default_rng(12345) # Constuctor for random number generator
data = rng.standard_normal((6,4))
data

array([[-1.52806807, -2.12830824,  0.17079098,  1.52434947],
       [-0.37376285, -0.7907664 , -1.83261326,  1.05956423],
       [-1.33906271, -1.15205485,  1.17433697,  0.97300629],
       [-0.0765475 , -0.90016214,  1.87390484, -0.55568907],
       [ 1.70222016,  0.31423687,  1.14348019,  2.13405389],
       [ 0.90144262,  0.0264819 ,  0.28903661, -0.96705004]])

In [82]:
# Use the NumPy array and dates to create a DataFrame
# df is the a conventional name for a DataFrame
df_ts = pd.DataFrame(data, index=dates, columns=list('ABCD'))
df_ts

A         B         C         D
2020-01-01 -1.528068 -2.128308  0.170791  1.524349
2020-01-02 -0.373763 -0.790766 -1.832613  1.059564
2020-01-03 -1.339063 -1.152055  1.174337  0.973006
2020-01-04 -0.076548 -0.900162  1.873905 -0.555689
2020-01-05  1.702220  0.314237  1.143480  2.134054
2020-01-06  0.901443  0.026482  0.289037 -0.967050

Note that the _index_ and _columns_ parameters are optional.

#### Create a DataFrame by passing a Python dictionary object

In [83]:
df_dict = pd.DataFrame({'A':1.,
                        'B':pd.Timestamp('20200101'),
                        'C':np.array([4] * 4, dtype='int32'),
                        'D':pd.Series(1, index=list(range(4)), dtype='float32'),
                        'E':pd.Categorical(['test', 'train', 'test','train']),
                        'F':'foo'
                       })
df_dict

A          B  C    D      E    F
0  1.0 2020-01-01  4  1.0   test  foo
1  1.0 2020-01-01  4  1.0  train  foo
2  1.0 2020-01-01  4  1.0   test  foo
3  1.0 2020-01-01  4  1.0  train  foo

In [84]:
df_dict.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   A       4 non-null      float64       
 1   B       4 non-null      datetime64[ns]
 2   C       4 non-null      int32         
 3   D       4 non-null      float32       
 4   E       4 non-null      category      
 5   F       4 non-null      object        
dtypes: category(1), datetime64[ns](1), float32(1), float64(1), int32(1), object(1)
memory usage: 260.0+ bytes


#### Read from CSV
Note: View documentation on I/O here: https://pandas.pydata.org/pandas-docs/stable/reference/io.html

Data source: Source: https://coronavirus.jhu.edu/data/new-cases

In [85]:
path = 'time_series_covid19_confirmed_global.csv'
df = pd.read_csv(path)

#### View the data types, first and last few rows of DF, and sample of DF rows

View the data types of each column with the `dtypes` attribute.

In [86]:
df.dtypes

Province/State     object
Country/Region     object
Lat               float64
Long              float64
1/22/20             int64
                   ...   
8/27/20             int64
8/28/20             int64
8/29/20             int64
8/30/20             int64
8/31/20             int64
Length: 227, dtype: object

In [87]:
df.shape

(266, 227)

See the index values with the `index` attribute.

In [88]:
# Use .index to show the index values
df.index

RangeIndex(start=0, stop=266, step=1)

In [89]:
df.index

RangeIndex(start=0, stop=266, step=1)

See the first few rows with `head()`.

In [90]:
df.head()

Province/State Country/Region       Lat       Long  1/22/20  1/23/20  \
0            NaN    Afghanistan  33.93911  67.709953        0        0   
1            NaN        Albania  41.15330  20.168300        0        0   
2            NaN        Algeria  28.03390   1.659600        0        0   
3            NaN        Andorra  42.50630   1.521800        0        0   
4            NaN         Angola -11.20270  17.873900        0        0   

   1/24/20  1/25/20  1/26/20  1/27/20  ...  8/22/20  8/23/20  8/24/20  \
0        0        0        0        0  ...    37953    37999    38054   
1        0        0        0        0  ...     8275     8427     8605   
2        0        0        0        0  ...    41068    41460    41858   
3        0        0        0        0  ...     1045     1045     1060   
4        0        0        0        0  ...     2134     2171     2222   

   8/25/20  8/26/20  8/27/20  8/28/20  8/29/20  8/30/20  8/31/20  
0    38070    38113    38129    38140    38143    38162    38165  
1     8759     8927     9083     9195     9279     9380     9513  
2    42228    42619    43016    43403    43781    44146    44494  
3     1060     1098     1098     1124     1124     1124     1176  
4     2283     2332     2415     2471     2551     2624     2654  

[5 rows x 227 columns]

In [91]:
df = pd.melt(df,id_vars=['Province/State','Country/Region','Lat','Long'], var_name='Date', value_name='Cases')
df.head(5)

Province/State Country/Region       Lat       Long     Date  Cases
0            NaN    Afghanistan  33.93911  67.709953  1/22/20      0
1            NaN        Albania  41.15330  20.168300  1/22/20      0
2            NaN        Algeria  28.03390   1.659600  1/22/20      0
3            NaN        Andorra  42.50630   1.521800  1/22/20      0
4            NaN         Angola -11.20270  17.873900  1/22/20      0

Use the `info()` function to get a general overview of the DataFrame.

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59318 entries, 0 to 59317
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Province/State  18063 non-null  object 
 1   Country/Region  59318 non-null  object 
 2   Lat             59318 non-null  float64
 3   Long            59318 non-null  float64
 4   Date            59318 non-null  object 
 5   Cases           59318 non-null  int64  
dtypes: float64(2), int64(1), object(3)
memory usage: 2.7+ MB


The `head()` method shows the first fiew (default is 5) of each column. Similarly, the `tail()` method shows the last few rows. 

In [93]:
# .head(n): return the first n (default 5) rows for each column
df.head()

Province/State Country/Region       Lat       Long     Date  Cases
0            NaN    Afghanistan  33.93911  67.709953  1/22/20      0
1            NaN        Albania  41.15330  20.168300  1/22/20      0
2            NaN        Algeria  28.03390   1.659600  1/22/20      0
3            NaN        Andorra  42.50630   1.521800  1/22/20      0
4            NaN         Angola -11.20270  17.873900  1/22/20      0

In [94]:
# .tail(n): return the last n (default 5) rows for each column
df.tail()

Province/State      Country/Region        Lat       Long     Date  Cases
59313            NaN  West Bank and Gaza  31.952200  35.233200  8/31/20  22729
59314            NaN      Western Sahara  24.215500 -12.885800  8/31/20     10
59315            NaN               Yemen  15.552727  48.516388  8/31/20   1958
59316            NaN              Zambia -13.133897  27.849332  8/31/20  12097
59317            NaN            Zimbabwe -19.015438  29.154857  8/31/20   6497

Use `sample()` to randomly sample a number of rows.

In [95]:
# Use .sample(n) to randomly samples n rows (default value is 1)
df.sample(3)

Province/State Country/Region      Lat      Long     Date  Cases
35543                NaN  Liechtenstein  47.1400    9.5500   6/3/20     82
14911  Western Australia      Australia -31.9505  115.8605  3/18/20     35
43104    South Australia      Australia -34.9285  138.6007   7/2/20    443

Don't forget, you can view the docstring with the `?` operator or `help()`.

In [96]:
# ?df.sample

### Accessing data
#### Selecting columns
Square-bracket syntax `[]` and dot notation `.` provide quick/easy access.

In [97]:
# Select a single column by name
df['Cases']
# df[['Cases']]

0            0
1            0
2            0
3            0
4            0
         ...  
59313    22729
59314       10
59315     1958
59316    12097
59317     6497
Name: Cases, Length: 59318, dtype: int64

In [98]:
# dot notation returns the same Series
df.Cases

0            0
1            0
2            0
3            0
4            0
         ...  
59313    22729
59314       10
59315     1958
59316    12097
59317     6497
Name: Cases, Length: 59318, dtype: int64

#### Select multiple columns

In [99]:
df[['Country/Region', 'Date', 'Cases']]

Country/Region     Date  Cases
0             Afghanistan  1/22/20      0
1                 Albania  1/22/20      0
2                 Algeria  1/22/20      0
3                 Andorra  1/22/20      0
4                  Angola  1/22/20      0
...                   ...      ...    ...
59313  West Bank and Gaza  8/31/20  22729
59314      Western Sahara  8/31/20     10
59315               Yemen  8/31/20   1958
59316              Zambia  8/31/20  12097
59317            Zimbabwe  8/31/20   6497

[59318 rows x 3 columns]

**Select rows** of data with the slice operator `[:]`.

In [100]:
# Select rows using the slice operator
df[0:5]

Province/State Country/Region       Lat       Long     Date  Cases
0            NaN    Afghanistan  33.93911  67.709953  1/22/20      0
1            NaN        Albania  41.15330  20.168300  1/22/20      0
2            NaN        Algeria  28.03390   1.659600  1/22/20      0
3            NaN        Andorra  42.50630   1.521800  1/22/20      0
4            NaN         Angola -11.20270  17.873900  1/22/20      0

#### `.loc[]` and `.iloc[]`
pandas recommends using `loc[]` and `iloc[]` for production code.

Use `loc[]` to select by name.

In [101]:
# Using .loc[]
df.loc[:,'Country/Region']

0               Afghanistan
1                   Albania
2                   Algeria
3                   Andorra
4                    Angola
                ...        
59313    West Bank and Gaza
59314        Western Sahara
59315                 Yemen
59316                Zambia
59317              Zimbabwe
Name: Country/Region, Length: 59318, dtype: object

In [102]:
# Get all rows for columns Age and Sex
df.loc[:,['Country/Region','Cases']]

Country/Region  Cases
0             Afghanistan      0
1                 Albania      0
2                 Algeria      0
3                 Andorra      0
4                  Angola      0
...                   ...    ...
59313  West Bank and Gaza  22729
59314      Western Sahara     10
59315               Yemen   1958
59316              Zambia  12097
59317            Zimbabwe   6497

[59318 rows x 2 columns]

In [103]:
# Get the first 5 rows for the specified columns
df.loc[0:5,['Country/Region','Cases']]

Country/Region  Cases
0          Afghanistan      0
1              Albania      0
2              Algeria      0
3              Andorra      0
4               Angola      0
5  Antigua and Barbuda      0

In [104]:
# Get row indexed 0,3, and 5 (all columns)
df.loc[[0,3,5], :]

Province/State       Country/Region       Lat       Long     Date  Cases
0            NaN          Afghanistan  33.93911  67.709953  1/22/20      0
3            NaN              Andorra  42.50630   1.521800  1/22/20      0
5            NaN  Antigua and Barbuda  17.06080 -61.796400  1/22/20      0

Use `iloc[]` to select by index.

In [105]:
# Select by position with .iloc[]
df.iloc[:,3]

0        67.709953
1        20.168300
2         1.659600
3         1.521800
4        17.873900
           ...    
59313    35.233200
59314   -12.885800
59315    48.516388
59316    27.849332
59317    29.154857
Name: Long, Length: 59318, dtype: float64

In [106]:
df.iloc[0:2,0:4]

Province/State Country/Region       Lat       Long
0            NaN    Afghanistan  33.93911  67.709953
1            NaN        Albania  41.15330  20.168300

In [107]:
# Get noncontiguous rows
df.iloc[[0,3],:]

Province/State Country/Region       Lat       Long     Date  Cases
0            NaN    Afghanistan  33.93911  67.709953  1/22/20      0
3            NaN        Andorra  42.50630   1.521800  1/22/20      0

### Filtering

#### Boolean Indexing

In [108]:
df.sample(5)

Province/State Country/Region      Lat     Long     Date  Cases
47909            NaN       Botswana -22.3285  24.6849  7/20/20    522
45140          Aruba    Netherlands  12.5211 -69.9683   7/9/20    105
56874            NaN        Senegal  14.4974 -14.4524  8/22/20  12850
34998            NaN         Jordan  31.2400  36.5100   6/1/20    746
32154            NaN     Tajikistan  38.8610  71.2761  5/21/20   2350

In [109]:
# This Boolean Series acts as a filter on the DataFrame
# Conditionally select records
df.loc[df['Cases']>100]

Province/State      Country/Region        Lat        Long     Date  \
69             Hubei               China  30.975600  112.270700  1/22/20   
335            Hubei               China  30.975600  112.270700  1/23/20   
601            Hubei               China  30.975600  112.270700  1/24/20   
867            Hubei               China  30.975600  112.270700  1/25/20   
1125       Guangdong               China  23.341700  113.424400  1/26/20   
...              ...                 ...        ...         ...      ...   
59312            NaN             Vietnam  14.058324  108.277199  8/31/20   
59313            NaN  West Bank and Gaza  31.952200   35.233200  8/31/20   
59315            NaN               Yemen  15.552727   48.516388  8/31/20   
59316            NaN              Zambia -13.133897   27.849332  8/31/20   
59317            NaN            Zimbabwe -19.015438   29.154857  8/31/20   

       Cases  
69       444  
335      444  
601      549  
867      761  
1125     111  
...      ...  
59312   1044  
59313  22729  
59315   1958  
59316  12097  
59317   6497  

[35480 rows x 6 columns]

In [110]:
df.loc[df['Country/Region']=='US']

Province/State Country/Region   Lat   Long     Date    Cases
242              NaN             US  40.0 -100.0  1/22/20        1
508              NaN             US  40.0 -100.0  1/23/20        1
774              NaN             US  40.0 -100.0  1/24/20        2
1040             NaN             US  40.0 -100.0  1/25/20        2
1306             NaN             US  40.0 -100.0  1/26/20        5
...              ...            ...   ...    ...      ...      ...
58230            NaN             US  40.0 -100.0  8/27/20  5867785
58496            NaN             US  40.0 -100.0  8/28/20  5913941
58762            NaN             US  40.0 -100.0  8/29/20  5961094
59028            NaN             US  40.0 -100.0  8/30/20  5996431
59294            NaN             US  40.0 -100.0  8/31/20  6030587

[223 rows x 6 columns]

In [111]:
# Return values based on two criteria: Sex == female and Survived == 1
df.loc[(df['Country/Region']=='United Kingdom') & (df['Cases']<=100)]

Province/State  Country/Region        Lat       Long  \
246                       Anguilla  United Kingdom  18.220600 -63.068600   
247                        Bermuda  United Kingdom  32.307800 -64.750500   
248         British Virgin Islands  United Kingdom  18.420700 -64.640000   
249                 Cayman Islands  United Kingdom  19.313300 -81.254600   
250                Channel Islands  United Kingdom  49.372300  -2.364400   
...                            ...             ...        ...        ...   
59040                   Montserrat  United Kingdom  16.742498 -62.187366   
59298                     Anguilla  United Kingdom  18.220600 -63.068600   
59300       British Virgin Islands  United Kingdom  18.420700 -64.640000   
59303  Falkland Islands (Malvinas)  United Kingdom -51.796300 -59.523600   
59306                   Montserrat  United Kingdom  16.742498 -62.187366   

          Date  Cases  
246    1/22/20      0  
247    1/22/20      0  
248    1/22/20      0  
249    1/22/20      0  
250    1/22/20      0  
...        ...    ...  
59040  8/30/20     13  
59298  8/31/20      3  
59300  8/31/20     47  
59303  8/31/20     13  
59306  8/31/20     13  

[1546 rows x 6 columns]

### Reset the index

In [112]:
tmp = df.sample(5).copy()
tmp

Province/State Country/Region        Lat       Long     Date   Cases
26902            NaN     Cabo Verde  16.538800 -23.041800   5/2/20     152
23409            NaN        Albania  41.153300  20.168300  4/19/20     562
33516            NaN    Afghanistan  33.939110  67.709953  5/27/20   12456
52674            NaN      Argentina -38.416100 -63.616700   8/7/20  235677
12914            NaN           Iraq  33.223191  43.679291  3/10/20      71

In [113]:
tmp.reset_index(drop=True, inplace=True)
tmp

Province/State Country/Region        Lat       Long     Date   Cases
0            NaN     Cabo Verde  16.538800 -23.041800   5/2/20     152
1            NaN        Albania  41.153300  20.168300  4/19/20     562
2            NaN    Afghanistan  33.939110  67.709953  5/27/20   12456
3            NaN      Argentina -38.416100 -63.616700   8/7/20  235677
4            NaN           Iraq  33.223191  43.679291  3/10/20      71

### Dropping entries
The `drop()` method creates a new object without the specified entries.

In [114]:
tmp.drop([1,4]) # drops the rows at index 1 and 4

Province/State Country/Region       Lat       Long     Date   Cases
0            NaN     Cabo Verde  16.53880 -23.041800   5/2/20     152
2            NaN    Afghanistan  33.93911  67.709953  5/27/20   12456
3            NaN      Argentina -38.41610 -63.616700   8/7/20  235677

In [115]:
df.drop(['Province/State'], axis=1) # drops the 'Ticket' column

Country/Region        Lat       Long     Date  Cases
0             Afghanistan  33.939110  67.709953  1/22/20      0
1                 Albania  41.153300  20.168300  1/22/20      0
2                 Algeria  28.033900   1.659600  1/22/20      0
3                 Andorra  42.506300   1.521800  1/22/20      0
4                  Angola -11.202700  17.873900  1/22/20      0
...                   ...        ...        ...      ...    ...
59313  West Bank and Gaza  31.952200  35.233200  8/31/20  22729
59314      Western Sahara  24.215500 -12.885800  8/31/20     10
59315               Yemen  15.552727  48.516388  8/31/20   1958
59316              Zambia -13.133897  27.849332  8/31/20  12097
59317            Zimbabwe -19.015438  29.154857  8/31/20   6497

[59318 rows x 5 columns]

### Sorting and Ranking

#### Sorting
* Use `sort_index` to sort lexicographically by row or column index
* Use `sort_values` to sort by the values in one or more columns.

The data is sorted in ascending order by default. Use the optional parameter-value `ascending = True` to sort in descending order.

In [116]:
df.sort_index(axis=0, ascending=False).head()

Province/State      Country/Region        Lat       Long     Date  Cases
59317            NaN            Zimbabwe -19.015438  29.154857  8/31/20   6497
59316            NaN              Zambia -13.133897  27.849332  8/31/20  12097
59315            NaN               Yemen  15.552727  48.516388  8/31/20   1958
59314            NaN      Western Sahara  24.215500 -12.885800  8/31/20     10
59313            NaN  West Bank and Gaza  31.952200  35.233200  8/31/20  22729

In [117]:
df.sort_values(by=['Cases', 'Date'], ascending=[False, True]).head(10)

Province/State Country/Region   Lat   Long     Date    Cases
59294            NaN             US  40.0 -100.0  8/31/20  6030587
59028            NaN             US  40.0 -100.0  8/30/20  5996431
58762            NaN             US  40.0 -100.0  8/29/20  5961094
58496            NaN             US  40.0 -100.0  8/28/20  5913941
58230            NaN             US  40.0 -100.0  8/27/20  5867785
57964            NaN             US  40.0 -100.0  8/26/20  5821819
57698            NaN             US  40.0 -100.0  8/25/20  5777710
57432            NaN             US  40.0 -100.0  8/24/20  5739536
57166            NaN             US  40.0 -100.0  8/23/20  5701645
56900            NaN             US  40.0 -100.0  8/22/20  5667070

**Ranking** assigns ranks from one through the number of valid data points in an array. By default, equal values are a rank that is the average of the ranks of those values. This can be adjusted with the `method` parameter.

Example from [pandas docs](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rank.html).

In [118]:
tmp = pd.DataFrame(data={'Animal': ['cat', 'penguin', 'dog', 'spider', 'snake'],
                         'Number_legs': [4, 2, 4, 8, np.nan]})
tmp

Animal  Number_legs
0      cat          4.0
1  penguin          2.0
2      dog          4.0
3   spider          8.0
4    snake          NaN

In [119]:
tmp['default_rank'] = tmp['Number_legs'].rank()
tmp['max_rank'] = tmp['Number_legs'].rank(method='max') # highest rank in the group
tmp['NA_bottom'] = tmp['Number_legs'].rank(na_option='bottom')
tmp['pct_rank'] = tmp['Number_legs'].rank(pct=True) # displays rankings in percentile form
tmp

Animal  Number_legs  default_rank  max_rank  NA_bottom  pct_rank
0      cat          4.0           2.5       3.0        2.5     0.625
1  penguin          2.0           1.0       1.0        1.0     0.250
2      dog          4.0           2.5       3.0        2.5     0.625
3   spider          8.0           4.0       4.0        4.0     1.000
4    snake          NaN           NaN       NaN        5.0       NaN

## Operations
Pandas inherits much of the NumPy functionality, including **ufuncs** (Universal Functions). However, there are two important items to note.
1. In pandas, ufuncs will preserve index and column labels for unary operations (negation, trig functions, etc.). 
2. Pandas automatically aligns indices for binary operations (addition, multiplication, etc.).

### Unary Ufuncs

In [120]:
s = pd.Series([4,3,-5,8], index=['a','b','c','d'])
s

a    4
b    3
c   -5
d    8
dtype: int64

In [121]:
s.abs()

a    4
b    3
c    5
d    8
dtype: int64

In [122]:
s.pow(3) # s^3

a     64
b     27
c   -125
d    512
dtype: int64

### Binary ufuncs
Arithmetic operations between pandas objects and scalars or arrays and other pandas objects of the same size work as expected.

In [123]:
s + 1

a    5
b    4
c   -4
d    9
dtype: int64

When two Series are used in an arithmetic operation, pandas aligns the indices to execute the operation. 

In the example below, there are non-overlapping indices. The result is the union of the index pairs.

In [124]:
s * pd.Series({'a':1, 'b':2,'c':3, 'e':4})

a     4.0
b     6.0
c   -15.0
d     NaN
e     NaN
dtype: float64

To specify a value to use instead of `NaN`, use the corresponding ufunc and the `fill_value` parameter.

In [125]:
s.mul(pd.Series({'a':1, 'b':2,'c':3, 'e':4}), fill_value=0)

a     4.0
b     6.0
c   -15.0
d     0.0
e     0.0
dtype: float64

### Descriptive statistics

In [126]:
# import statsmodels.api as sm
print(sm.datasets.anes96.NOTE)
# data = sm.datasets.anes96.load_pandas()
# anes = data.data

::

    Number of observations - 944
    Number of variables - 10

    Variables name definitions::

            popul - Census place population in 1000s
            TVnews - Number of times per week that respondent watches TV news.
            PID - Party identification of respondent.
                0 - Strong Democrat
                1 - Weak Democrat
                2 - Independent-Democrat
                3 - Independent-Indpendent
                4 - Independent-Republican
                5 - Weak Republican
                6 - Strong Republican
            age : Age of respondent.
            educ - Education level of respondent
                1 - 1-8 grades
                2 - Some high school
                3 - High school graduate
                4 - Some college
                5 - College degree
                6 - Master's degree
                7 - PhD
            income - Income of household
                1  - None or less than $2,999
                2  - $3,000-$4,9

In [127]:
anes.sample(10)

popul  TVnews  selfLR  ClinLR  DoleLR  PID       age  educ  income  vote  \
404    0.0     7.0     4.0     3.0     5.0  0.0  1.398560   3.0    16.0   0.0   
553   35.0     0.0     3.0     4.0     6.0  1.0 -0.672788   7.0    19.0   0.0   
662  190.0     1.0     6.0     2.0     6.0  6.0 -0.733710   3.0    20.0   1.0   
787    0.0     1.0     6.0     2.0     5.0  6.0 -0.733710   7.0    22.0   1.0   
224  170.0     2.0     4.0     4.0     4.0  0.0  0.362886   3.0    13.0   1.0   
363  640.0     5.0     4.0     4.0     6.0  0.0 -1.403852   6.0    16.0   0.0   
24    19.0     0.0     4.0     2.0     2.0  1.0 -0.124490   3.0     2.0   0.0   
149    5.0     7.0     4.0     4.0     7.0  0.0  1.398560   3.0    10.0   0.0   
674  110.0     6.0     6.0     2.0     6.0  6.0 -0.794632   7.0    21.0   1.0   
936    0.0     7.0     6.0     2.0     6.0  6.0 -0.368178   4.0    24.0   1.0   

     logpopul  
404 -2.302585  
553  3.558201  
662  5.247550  
787 -2.302585  
224  5.136386  
363  6.461624  
24   2.949688  
149  1.629241  
674  4.701389  
936 -2.302585

See a quick statistical summary of numeric columns with `describe()`.

In [128]:
anes.describe()

popul      TVnews      selfLR      ClinLR      DoleLR  \
count   944.000000  944.000000  944.000000  944.000000  944.000000   
mean    306.381356    3.727754    4.325212    2.939619    5.394068   
std    1082.606745    2.677235    1.438436    1.383725    1.269349   
min       0.000000    0.000000    1.000000    1.000000    1.000000   
25%       1.000000    1.000000    3.000000    2.000000    5.000000   
50%      22.000000    3.000000    4.000000    3.000000    6.000000   
75%     110.000000    7.000000    6.000000    4.000000    6.000000   
max    7300.000000    7.000000    7.000000    7.000000    7.000000   

              PID           age        educ      income        vote  \
count  944.000000  9.440000e+02  944.000000  944.000000  944.000000   
mean     2.842161 -1.300749e-16    4.565678   16.331568    0.416314   
std      2.273337  1.000530e+00    1.599287    5.974781    0.493208   
min      0.000000 -1.708462e+00    1.000000    1.000000    0.000000   
25%      1.000000 -7.946321e-01    3.000000   14.000000    0.000000   
50%      2.000000 -1.854120e-01    4.000000   17.000000    0.000000   
75%      5.000000  6.674961e-01    6.000000   21.000000    1.000000   
max      6.000000  2.677922e+00    7.000000   24.000000    1.000000   

         logpopul  
count  944.000000  
mean     2.472307  
std      3.187043  
min     -2.302585  
25%      0.095310  
50%      3.095578  
75%      4.701389  
max      8.895643

In [129]:
# View the mean, standard deviation, median, min, max, and more...
anes.loc[:,'popul'].mean()

306.3813559322034

In [130]:
anes.loc[:,'popul'].std()

1082.606745077667

In [131]:
anes.loc[:, ['popul','TVnews']].median()

popul     22.0
TVnews     3.0
dtype: float64

In [132]:
anes.min()

popul       0.000000
TVnews      0.000000
selfLR      1.000000
ClinLR      1.000000
DoleLR      1.000000
PID         0.000000
age        -1.708462
educ        1.000000
income      1.000000
vote        0.000000
logpopul   -2.302585
dtype: float64

### Correlation and Covariance
Use the `cov()` function to retrieve the covariance or covariance matrix. Use the `corr()` function to return the correlation matrix.

In [133]:
anes['popul'].cov(anes['selfLR'])

-102.49318798641191

In [134]:
anes.cov()

popul     TVnews      selfLR     ClinLR     DoleLR  \
popul     1.172037e+06  59.292692 -102.493188  29.140761  35.232381   
TVnews    5.929269e+01   7.167585   -0.041803   0.007934  -0.047428   
selfLR   -1.024932e+02  -0.041803    2.069099  -0.312262  -0.164347   
ClinLR    2.914076e+01   0.007934   -0.312262   1.914696  -0.619871   
DoleLR    3.523238e+01  -0.047428   -0.164347  -0.619871   1.611248   
PID      -2.204933e+02  -0.318732    2.022754  -1.256624   0.138617   
age      -4.735627e+01   1.094991    0.136229  -0.045063  -0.034250   
educ     -6.699517e+00  -0.248803   -0.243545  -0.456794   0.377060   
income   -1.164882e+02  -1.000835    0.295025  -1.861188   1.091895   
vote     -3.901365e+01  -0.019096    0.413777  -0.318420   0.011804   
logpopul  1.603573e+03  -0.013524   -0.534240   0.491234   0.184814   

                 PID        age      educ      income       vote     logpopul  
popul    -220.493296 -47.356275 -6.699517 -116.488191 -39.013651  1603.573237  
TVnews     -0.318732   1.094991 -0.248803   -1.000835  -0.019096    -0.013524  
selfLR      2.022754   0.136229 -0.243545    0.295025   0.413777    -0.534240  
ClinLR     -1.256624  -0.045063 -0.456794   -1.861188  -0.318420     0.491234  
DoleLR      0.138617  -0.034250  0.377060    1.091895   0.011804     0.184814  
PID         5.168061   0.018249  0.376761    2.838180   0.893988    -1.224058  
age         0.018249   1.001060 -0.254166   -0.469261   0.026483    -0.073819  
educ        0.376761  -0.254166  2.557718    3.561975   0.067538    -0.079417  
income      2.838180  -0.469261  3.561975   35.698006   0.560651    -1.618909  
vote        0.893988   0.026483  0.067538    0.560651   0.243254    -0.270326  
logpopul   -1.224058  -0.073819 -0.079417   -1.618909  -0.270326    10.157246

In [135]:
anes.corr()

popul    TVnews    selfLR    ClinLR    DoleLR       PID  \
popul     1.000000  0.020457 -0.065816  0.019453  0.025638 -0.089590   
TVnews    0.020457  1.000000 -0.010855  0.002142 -0.013956 -0.052369   
selfLR   -0.065816 -0.010855  1.000000 -0.156884 -0.090010  0.618570   
ClinLR    0.019453  0.002142 -0.156884  1.000000 -0.352915 -0.399477   
DoleLR    0.025638 -0.013956 -0.090010 -0.352915  1.000000  0.048037   
PID      -0.089590 -0.052369  0.618570 -0.399477  0.048037  1.000000   
age      -0.043720  0.408784  0.094656 -0.032549 -0.026968  0.008023   
educ     -0.003869 -0.058109 -0.105868 -0.206416  0.185739  0.103628   
income   -0.018009 -0.062568  0.034328 -0.225122  0.143972  0.208956   
vote     -0.073066 -0.014462  0.583238 -0.466574  0.018855  0.797329   
logpopul  0.464761 -0.001585 -0.116535  0.111391  0.045684 -0.168947   

               age      educ    income      vote  logpopul  
popul    -0.043720 -0.003869 -0.018009 -0.073066  0.464761  
TVnews    0.408784 -0.058109 -0.062568 -0.014462 -0.001585  
selfLR    0.094656 -0.105868  0.034328  0.583238 -0.116535  
ClinLR   -0.032549 -0.206416 -0.225122 -0.466574  0.111391  
DoleLR   -0.026968  0.185739  0.143972  0.018855  0.045684  
PID       0.008023  0.103628  0.208956  0.797329 -0.168947  
age       1.000000 -0.158841 -0.078499  0.053668 -0.023150  
educ     -0.158841  1.000000  0.372771  0.085624 -0.015581  
income   -0.078499  0.372771  1.000000  0.190257 -0.085018  
vote      0.053668  0.085624  0.190257  1.000000 -0.171977  
logpopul -0.023150 -0.015581 -0.085018 -0.171977  1.000000

The default method for `corr()` is Pearson correlation coefficient. Other available methods include Kendall Tau correlation coefficient (`kendall`) and Spearman rank correlation (`spearman`).

### Missing data
* `isnull()`: Generate a boolean mask indicating missing values
* `notnull()`: Opposite of `isnull()`
* `dropna()`: Return a filtered version of the data
* `fillna()`: Return a copy of the data with missing values filled or imputed

Example data from [pandas docs](https://pandas.pydata.org/pandas-docs/stable/user_guide/missing_data.html).

In [136]:
tmp.loc['b', 'two'] = 123

In [137]:
tmp = pd.DataFrame(np.random.randn(5, 3),
                  index=["a", "c", "e", "f", "h"],
                  columns=["one", "two", "three"])
tmp["four"] = "bar"
tmp["five"] = tmp["one"] > 0

tmp = tmp.reindex(["a", "b", "c", "d", "e", "f", "g", "h"])
tmp.loc['b', 'two'] = 2
tmp.loc['b', 'three'] = 3

tmp

one       two     three four   five
a  0.387294 -0.381033  1.183318  bar   True
b       NaN  2.000000  3.000000  NaN    NaN
c -0.972071 -0.480584 -0.937405  bar  False
d       NaN       NaN       NaN  NaN    NaN
e -1.166793 -0.599566  0.677479  bar  False
f  1.278766 -0.194974 -1.015254  bar   True
g       NaN       NaN       NaN  NaN    NaN
h -1.230681 -1.864915 -4.048592  bar  False

See sum of missing values per column.

In [138]:
tmp.isnull().sum(axis=0)

one      3
two      2
three    2
four     3
five     3
dtype: int64

Return rows with a missing value in the `one` column.

In [139]:
tmp[tmp['one'].isnull()]

one  two  three four five
b  NaN  2.0    3.0  NaN  NaN
d  NaN  NaN    NaN  NaN  NaN
g  NaN  NaN    NaN  NaN  NaN

Show all rows with `any` missing values.

In [140]:
# Show all rows with `any` missing values.
tmp[tmp.isnull().any(axis=1)]

one  two  three four five
b  NaN  2.0    3.0  NaN  NaN
d  NaN  NaN    NaN  NaN  NaN
g  NaN  NaN    NaN  NaN  NaN

Drop rows with at least one missing values.

In [141]:
tmp.dropna()

one       two     three four   five
a  0.387294 -0.381033  1.183318  bar   True
c -0.972071 -0.480584 -0.937405  bar  False
e -1.166793 -0.599566  0.677479  bar  False
f  1.278766 -0.194974 -1.015254  bar   True
h -1.230681 -1.864915 -4.048592  bar  False

Fill missing values with 0.

In [142]:
tmp.fillna(0)

one       two     three four   five
a  0.387294 -0.381033  1.183318  bar   True
b  0.000000  2.000000  3.000000    0      0
c -0.972071 -0.480584 -0.937405  bar  False
d  0.000000  0.000000  0.000000    0      0
e -1.166793 -0.599566  0.677479  bar  False
f  1.278766 -0.194974 -1.015254  bar   True
g  0.000000  0.000000  0.000000    0      0
h -1.230681 -1.864915 -4.048592  bar  False

Fill missing values with the value in the previous row.

In [143]:
tmp.fillna(method='ffill')

one       two     three four   five
a  0.387294 -0.381033  1.183318  bar   True
b  0.387294  2.000000  3.000000  bar   True
c -0.972071 -0.480584 -0.937405  bar  False
d -0.972071 -0.480584 -0.937405  bar  False
e -1.166793 -0.599566  0.677479  bar  False
f  1.278766 -0.194974 -1.015254  bar   True
g  1.278766 -0.194974 -1.015254  bar   True
h -1.230681 -1.864915 -4.048592  bar  False

Fill missing values with the median value.

In [144]:
tmp.fillna(tmp.median())

one       two     three four   five
a  0.387294 -0.381033  1.183318  bar   True
b -0.972071  2.000000  3.000000  NaN      0
c -0.972071 -0.480584 -0.937405  bar  False
d -0.972071 -0.430809 -0.129963  NaN      0
e -1.166793 -0.599566  0.677479  bar  False
f  1.278766 -0.194974 -1.015254  bar   True
g -0.972071 -0.430809 -0.129963  NaN      0
h -1.230681 -1.864915 -4.048592  bar  False

Fill missing values with one of the provided methods with `interpolate()`. 

In [145]:
tmp.interpolate(method='linear')

one       two     three four   five
a  0.387294 -0.381033  1.183318  bar   True
b -0.292389  2.000000  3.000000  NaN    NaN
c -0.972071 -0.480584 -0.937405  bar  False
d -1.069432 -0.540075 -0.129963  NaN    NaN
e -1.166793 -0.599566  0.677479  bar  False
f  1.278766 -0.194974 -1.015254  bar   True
g  0.024042 -1.029944 -2.531923  NaN    NaN
h -1.230681 -1.864915 -4.048592  bar  False

## Tidy Data - a standard way to organize data values within a dataset
Referernce: Hadley Wickham. "Tidy data". *The Journal of Statistical Software*, vol. 59, 2014 (https://vita.had.co.nz/papers/tidy-data.html)

Tidy data takes the following forms:
* Each variable forms a column.
* Each observation forms a row.
* Each type of observational unit forms a table.

Messy data is any other arrangement of the data.

Tidy data allows the analyst and computer to extract needed variables by providing a standard way of structuring a dataset. It is particularly useful for vectorized programming.

<img src='../../../Images/tidy.png' style='width: 400px;' align='left'/>

In [146]:
# Source: https://coronavirus.jhu.edu/data/new-cases
df = pd.read_csv('time_series_covid19_confirmed_global.csv')
df

Province/State      Country/Region        Lat       Long  1/22/20  \
0              NaN         Afghanistan  33.939110  67.709953        0   
1              NaN             Albania  41.153300  20.168300        0   
2              NaN             Algeria  28.033900   1.659600        0   
3              NaN             Andorra  42.506300   1.521800        0   
4              NaN              Angola -11.202700  17.873900        0   
..             ...                 ...        ...        ...      ...   
261            NaN  West Bank and Gaza  31.952200  35.233200        0   
262            NaN      Western Sahara  24.215500 -12.885800        0   
263            NaN               Yemen  15.552727  48.516388        0   
264            NaN              Zambia -13.133897  27.849332        0   
265            NaN            Zimbabwe -19.015438  29.154857        0   

     1/23/20  1/24/20  1/25/20  1/26/20  1/27/20  ...  8/22/20  8/23/20  \
0          0        0        0        0        0  ...    37953    37999   
1          0        0        0        0        0  ...     8275     8427   
2          0        0        0        0        0  ...    41068    41460   
3          0        0        0        0        0  ...     1045     1045   
4          0        0        0        0        0  ...     2134     2171   
..       ...      ...      ...      ...      ...  ...      ...      ...   
261        0        0        0        0        0  ...    18476    18802   
262        0        0        0        0        0  ...       10       10   
263        0        0        0        0        0  ...     1907     1911   
264        0        0        0        0        0  ...    10831    11082   
265        0        0        0        0        0  ...     5893     5930   

     8/24/20  8/25/20  8/26/20  8/27/20  8/28/20  8/29/20  8/30/20  8/31/20  
0      38054    38070    38113    38129    38140    38143    38162    38165  
1       8605     8759     8927     9083     9195     9279     9380     9513  
2      41858    42228    42619    43016    43403    43781    44146    44494  
3       1060     1060     1098     1098     1124     1124     1124     1176  
4       2222     2283     2332     2415     2471     2551     2624     2654  
..       ...      ...      ...      ...      ...      ...      ...      ...  
261    19213    19678    20155    20677    21251    21668    22204    22729  
262       10       10       10       10       10       10       10       10  
263     1916     1924     1930     1933     1943     1946     1953     1958  
264    11148    11285    11376    11601    11779    11902    12025    12097  
265     6070     6196     6251     6292     6388     6406     6412     6497  

[266 rows x 227 columns]

In [147]:
df = pd.melt(df,id_vars=['Province/State','Country/Region','Lat','Long'], var_name='Date', value_name='Cases')
df

Province/State      Country/Region        Lat       Long     Date  Cases
0                NaN         Afghanistan  33.939110  67.709953  1/22/20      0
1                NaN             Albania  41.153300  20.168300  1/22/20      0
2                NaN             Algeria  28.033900   1.659600  1/22/20      0
3                NaN             Andorra  42.506300   1.521800  1/22/20      0
4                NaN              Angola -11.202700  17.873900  1/22/20      0
...              ...                 ...        ...        ...      ...    ...
59313            NaN  West Bank and Gaza  31.952200  35.233200  8/31/20  22729
59314            NaN      Western Sahara  24.215500 -12.885800  8/31/20     10
59315            NaN               Yemen  15.552727  48.516388  8/31/20   1958
59316            NaN              Zambia -13.133897  27.849332  8/31/20  12097
59317            NaN            Zimbabwe -19.015438  29.154857  8/31/20   6497

[59318 rows x 6 columns]

### Categoricals
When we imported the Titanic data, the numeric data was read in as numeric and the character data read in as objects. 

In [148]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59318 entries, 0 to 59317
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Province/State  18063 non-null  object 
 1   Country/Region  59318 non-null  object 
 2   Lat             59318 non-null  float64
 3   Long            59318 non-null  float64
 4   Date            59318 non-null  object 
 5   Cases           59318 non-null  int64  
dtypes: float64(2), int64(1), object(3)
memory usage: 2.7+ MB


Let's change the defined data types to the appropriate type with `astype(...)`

In [149]:
df[['Country/Region', 'Province/State']] = df[['Country/Region', 'Province/State']].astype('category')

In [150]:
# View the types again
df.dtypes

Province/State    category
Country/Region    category
Lat                float64
Long               float64
Date                object
Cases                int64
dtype: object

#### Unique values with `unique()`

In [151]:
df.loc[:,'Country/Region'].unique()

['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', ..., 'West Bank and Gaza', 'Western Sahara', 'Yemen', 'Zambia', 'Zimbabwe']
Length: 188
Categories (188, object): ['Afghanistan', 'Albania', 'Algeria', 'Andorra', ..., 'Western Sahara', 'Yemen', 'Zambia', 'Zimbabwe']

#### Histogramming (value counts)

In [152]:
# Returns the frequency of each value
df.loc[:,'Country/Region'].value_counts()

China             7359
Canada            3122
France            2453
United Kingdom    2453
Australia         1784
                  ... 
Nepal              223
Namibia            223
Mozambique         223
Morocco            223
Afghanistan        223
Name: Country/Region, Length: 188, dtype: int64

Return the `mode`.

In [153]:
# Returns the most frequent value in the list
df.loc[:,'Country/Region'].mode()

0    China
Name: Country/Region, dtype: category
Categories (188, object): ['Afghanistan', 'Albania', 'Algeria', 'Andorra', ..., 'Western Sahara', 'Yemen', 'Zambia', 'Zimbabwe']